# Node base image
FROM node:latest
# Set working directory
WORKDIR /app
# Copy package files and install dependencies
COPY package*.json ./
RUN npm install
# Copy the rest of the code
COPY . .
# Start the Angular dev server
CMD ["npm", "start", "--", "--host", "0.0.0.0"]

