version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ng_dev:/app
    ports:
      - "4200:4200"
  backend:
    build:
      context: ./pb
      args:
        TARGETOS: linux
        TARGETARCH: amd64
    ports:
      - "8090:8090"

volumes:
  ng_dev:
